language: java

jdk:
  - oraclejdk7

before_install:
  - chmod +x gradlew
  - pip install --user codecov

script:
  - ./gradlew build --stacktrace

after_success:
  - codecov

notifications:
  email:
    on_failure: change